/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedTestTrackingRouteImport } from './routes/_authed.test-tracking'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { Route as ApiProxySplatRouteImport } from './routes/api/proxy/$'
import { Route as AuthedTestsNewRouteImport } from './routes/_authed.tests.new'
import { Route as AuthedTestsIdQuestionsRouteImport } from './routes/_authed.tests.$id.questions'
import { Route as AuthedTestsIdPreviewRouteImport } from './routes/_authed.tests.$id.preview'
import { Route as AuthedTestsIdEditRouteImport } from './routes/_authed.tests.$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTestTrackingRoute = AuthedTestTrackingRouteImport.update({
  id: '/test-tracking',
  path: '/test-tracking',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiProxySplatRoute = ApiProxySplatRouteImport.update({
  id: '/api/proxy/$',
  path: '/api/proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTestsNewRoute = AuthedTestsNewRouteImport.update({
  id: '/tests/new',
  path: '/tests/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTestsIdQuestionsRoute = AuthedTestsIdQuestionsRouteImport.update({
  id: '/tests/$id/questions',
  path: '/tests/$id/questions',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTestsIdPreviewRoute = AuthedTestsIdPreviewRouteImport.update({
  id: '/tests/$id/preview',
  path: '/tests/$id/preview',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTestsIdEditRoute = AuthedTestsIdEditRouteImport.update({
  id: '/tests/$id/edit',
  path: '/tests/$id/edit',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/test-tracking': typeof AuthedTestTrackingRoute
  '/tests/new': typeof AuthedTestsNewRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
  '/tests/$id/edit': typeof AuthedTestsIdEditRoute
  '/tests/$id/preview': typeof AuthedTestsIdPreviewRoute
  '/tests/$id/questions': typeof AuthedTestsIdQuestionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/test-tracking': typeof AuthedTestTrackingRoute
  '/tests/new': typeof AuthedTestsNewRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
  '/tests/$id/edit': typeof AuthedTestsIdEditRoute
  '/tests/$id/preview': typeof AuthedTestsIdPreviewRoute
  '/tests/$id/questions': typeof AuthedTestsIdQuestionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/test-tracking': typeof AuthedTestTrackingRoute
  '/_authed/tests/new': typeof AuthedTestsNewRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
  '/_authed/tests/$id/edit': typeof AuthedTestsIdEditRoute
  '/_authed/tests/$id/preview': typeof AuthedTestsIdPreviewRoute
  '/_authed/tests/$id/questions': typeof AuthedTestsIdQuestionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/test-tracking'
    | '/tests/new'
    | '/api/proxy/$'
    | '/tests/$id/edit'
    | '/tests/$id/preview'
    | '/tests/$id/questions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/test-tracking'
    | '/tests/new'
    | '/api/proxy/$'
    | '/tests/$id/edit'
    | '/tests/$id/preview'
    | '/tests/$id/questions'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/dashboard'
    | '/_authed/test-tracking'
    | '/_authed/tests/new'
    | '/api/proxy/$'
    | '/_authed/tests/$id/edit'
    | '/_authed/tests/$id/preview'
    | '/_authed/tests/$id/questions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiProxySplatRoute: typeof ApiProxySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/test-tracking': {
      id: '/_authed/test-tracking'
      path: '/test-tracking'
      fullPath: '/test-tracking'
      preLoaderRoute: typeof AuthedTestTrackingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/proxy/$': {
      id: '/api/proxy/$'
      path: '/api/proxy/$'
      fullPath: '/api/proxy/$'
      preLoaderRoute: typeof ApiProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/tests/new': {
      id: '/_authed/tests/new'
      path: '/tests/new'
      fullPath: '/tests/new'
      preLoaderRoute: typeof AuthedTestsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tests/$id/questions': {
      id: '/_authed/tests/$id/questions'
      path: '/tests/$id/questions'
      fullPath: '/tests/$id/questions'
      preLoaderRoute: typeof AuthedTestsIdQuestionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tests/$id/preview': {
      id: '/_authed/tests/$id/preview'
      path: '/tests/$id/preview'
      fullPath: '/tests/$id/preview'
      preLoaderRoute: typeof AuthedTestsIdPreviewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tests/$id/edit': {
      id: '/_authed/tests/$id/edit'
      path: '/tests/$id/edit'
      fullPath: '/tests/$id/edit'
      preLoaderRoute: typeof AuthedTestsIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedTestTrackingRoute: typeof AuthedTestTrackingRoute
  AuthedTestsNewRoute: typeof AuthedTestsNewRoute
  AuthedTestsIdEditRoute: typeof AuthedTestsIdEditRoute
  AuthedTestsIdPreviewRoute: typeof AuthedTestsIdPreviewRoute
  AuthedTestsIdQuestionsRoute: typeof AuthedTestsIdQuestionsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedTestTrackingRoute: AuthedTestTrackingRoute,
  AuthedTestsNewRoute: AuthedTestsNewRoute,
  AuthedTestsIdEditRoute: AuthedTestsIdEditRoute,
  AuthedTestsIdPreviewRoute: AuthedTestsIdPreviewRoute,
  AuthedTestsIdQuestionsRoute: AuthedTestsIdQuestionsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiProxySplatRoute: ApiProxySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
